### ISSUE TITLE
Visually hidden terminal is present in tab order and accessibility tree

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#245]
### Describe the bug

When terminal is hidden by default, it's still possible to navigate to that hidden element with keyboard or assistive technologies. Even writing commands to the terminal works.

### Steps to reproduce

1. Create lesson with:

```yaml
---
type: lesson
title: Default
mainCommand: ''
prepareCommands: []
terminal:
  panels: terminal
---

# Terminal test - Default
```

2. Navigate to `Toggle terminal` with keyboard
3. Navigate 2-3 tab stops more
4. Focus is now on visually invisible element
5. Write commands like `npm start`
6. Vite server from template starts

### Expected behavior

When terminal is not visually present, it should not be part of tab order or accessibility tree. Maybe it shouldn't even be in the DOM. 

### Screenshots

https://github.com/user-attachments/assets/2511a479-d49f-4413-9301-3a646676a9e2

### Platform

- TutorialKit version: 0.1.4
