### ISSUE TITLE
`Toggle Terminal` button should be hidden when `terminal: false`

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz/tutorialkit#300]
### Describe the bug

When terminal is disabled in metadata, the `Toggle Terminal` button is still visible. It just shows empty blank terminal when toggled.

### Steps to reproduce

1. Define in metadata:
  ```yaml
  ---
  type: lesson
  title: Test
  terminal: false
  ---
  ```
2. Open page and click `Toggle Terminal`

### Expected behavior

Whole `Toggle Terminal` button should be hidden. 

### Screenshots

![image](https://github.com/user-attachments/assets/143621a0-bd9b-46bf-86fc-db8d95f34482)

### Platform

- TutorialKit version: 0.2.1
