### ISSUE TITLE
No-editor layout column width

### ISSUE THREAD

**Issue by iliakan** [stackblitz/tutorialkit#319]
### Is your feature request related to a problem?

For informational lessons without editor, the text occupies the full width, which is too much.

### Describe the solution you'd like.

Content-oriented websites, such as https://medium.com/ and others limit a text column width.

![Uploading image.png…]()

How to do the same?

### Describe alternatives you've considered.

-

**Comment by AriPerkkio** [comment]
Does this layout look correct? https://stackblitz.com/~/edit/vitejs-vite-zhhoys?file=theme.css&file=src/content/tutorial/1-basics/1-introduction/1-welcome/content.md&terminal=dev

Add a `theme.css` and define your styles there:

```css
html {
    background-color: var(--tk-background-primary);
}

body {
    max-width: 600px;
    margin-inline: auto;
}
```

```yaml
---
type: lesson
title: Welcome to TutorialKit
editor: false
previews: false
terminal: false
---

# Welcom to TutorialKit

Lorem ipsum...
```

<img src="https://github.com/user-attachments/assets/77a0f913-ce4d-4f54-a409-14ecf5d113f3" width="480px" />

**Comment by iliakan** [comment]
Thank you. I see it's easy to do, but this column in this layout encompasses the whole website.

Usually, it's only the text which is columnized, not the header/footer.

Here's medium.com for example:

<img width="1717" alt="image" src="https://github.com/user-attachments/assets/f50a5413-ea0d-4f26-9d34-8b993c3d3086">

**Comment by AriPerkkio** [comment]
How about adding it directly into the `content.md` and not use `theme.css` at all?

```yaml
---
type: lesson
title: Welcome to TutorialKit
editor: false
previews: false
terminal: false
---

<div style="max-width: 680px; margin-inline: auto;">

# Welcom to TutorialKit

Lorem ipsum dolor...

</div>
```

<img src="https://github.com/user-attachments/assets/7b1fcdc1-15af-4026-9927-30f451863635" width="480px" />
